### ISSUE TITLE
Error: The "path" argument must be one of type string, Buffer, or URL. Received type undefined

### ISSUE THREAD

**Issue by dapperdandev** [xo-energy/action-octopus-build-information#22]
This error could be clarified. The only thing I can think of is that it wants me to provide a value for `output_path`, but the documentation makes it sound like it's optional.

> output_path: The path to an output directory. When present, this action writes these files:
${output_path}/buildInformation.json: the build information JSON.
${output_path}/buildInformationMapped-${package_id}.json: the full, mapped build information returned by the Octopus Deploy server after pushing build information for ${package_id}.

My configuration:

```yaml
      - name: Generate Octopus Deploy build information
        uses: xo-energy/action-octopus-build-information@v1.0.0
        with:
          octopus_api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
          octopus_server: ${{ secrets.OCTOPUSSERVERURL }}
          octopus_project: ${{ inputs.OCTOPUS_PROJECT }}
          push_package_ids: ${{ inputs.OCTOPUS_PROJECT }}
          push_version: ${{ env.PACKAGE_VERSION }}
```
