### ISSUE TITLE
Warning: Failed to fetch Octopus project: No project named 'x' was found

### ISSUE THREAD

**Issue by dapperdandev** [xo-energy/action-octopus-build-information#23]
All other Octo steps work just fine with my configuration. I tried with and w/o quotes around project names. Neither does the trick.

Could spaces in project names be causing issues?

```yaml
# ci.yml
name: CI
on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  ci_user:
    uses: ./.github/workflows/ci-shared.yml
    with:
      APP_NAME: user
      OCTOPUS_DEPLOY_TO: "Integration"
      OCTOPUS_PROJECT: "Kno2 Web - User"
      OCTOPUS_TENANT: "Central US"
    secrets:
      OCTOPUSSERVERAPIKEY: ${{ secrets.OCTOPUSSERVERAPIKEY }}
      OCTOPUSSERVERURL: ${{ secrets.OCTOPUSSERVERURL }}
```

```yaml
# ci-shared.yml
name: Build and Deploy

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      OCTOPUS_DEPLOY_TO:
        required: true
        type: string
      OCTOPUS_PROJECT:
        required: true
        type: string
      OCTOPUS_TENANT:
        required: true
        type: string

    secrets:
      OCTOPUSSERVERAPIKEY:
        required: true
      OCTOPUSSERVERURL:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    ...

     - name: Generate Octopus Deploy build information
        uses: xo-energy/action-octopus-build-information@v1.0.0
        with:
          octopus_api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
          octopus_server: ${{ secrets.OCTOPUSSERVERURL }}
          octopus_project: ${{ inputs.OCTOPUS_PROJECT }}
          output_path: octo
          push_package_ids: ${{ inputs.OCTOPUS_PROJECT }}
          push_version: ${{ env.PACKAGE_VERSION }} # Set in an earlier step
```

```
